"""
Step 3 - CFPB corpus profiling.

Run from the project root:
    python src/profile_corpus.py

What it does:
  1. Converts the 8.4 GB CSV to Parquet once (a few minutes, then never again).
     Malformed rows are captured rather than silently dropped, and the
     rejection rate is reported as a data quality finding.
  2. Runs the profile queries against the Parquet file (seconds).
  3. Writes docs/01_corpus_profile.md and prints everything to the console.

The four things we need out of this:
  - how many complaints actually carry a narrative (our usable subset)
  - how badly the Product and Issue classes are imbalanced
  - how long narratives run (drives chunking and cost)
  - how much of the text the XXXX redaction has eaten
"""

from pathlib import Path
import sys
import duckdb

ROOT = Path(__file__).resolve().parent.parent
RAW_CSV = ROOT / "data" / "raw" / "complaints.csv"
PARQUET = ROOT / "data" / "raw" / "complaints.parquet"
OUT_MD = ROOT / "docs" / "01_corpus_profile.md"

NARR = '"Consumer complaint narrative"'

report = []
reject_count = None


def emit(text=""):
    """Print to console and collect for the markdown report."""
    print(text)
    report.append(text)


def table(rows, headers):
    """Render a list of tuples as a markdown table."""
    emit("| " + " | ".join(headers) + " |")
    emit("|" + "|".join(["---"] * len(headers)) + "|")
    for r in rows:
        emit("| " + " | ".join("" if v is None else str(v) for v in r) + " |")
    emit()


def convert(con):
    """CSV to Parquet, capturing malformed rows instead of dropping them silently."""
    global reject_count

    print("Converting CSV to Parquet. This is a one-time step.")
    print("Expect roughly 3 to 8 minutes. Leave it running.\n")

    con.execute(f"""
        COPY (
            SELECT * FROM read_csv(
                '{RAW_CSV.as_posix()}',
                header = true,
                all_varchar = true,
                quote = '"',
                escape = '"',
                strict_mode = false,
                null_padding = true, parallel = false,
                store_rejects = true
            )
        )
        TO '{PARQUET.as_posix()}' (FORMAT PARQUET, COMPRESSION ZSTD)
    """)

    try:
        reject_count = con.execute("SELECT COUNT(*) FROM reject_errors").fetchone()[0]
    except Exception:
        reject_count = None

    size_gb = PARQUET.stat().st_size / 1024**3
    print(f"Done. Parquet is {size_gb:.2f} GB.")
    if reject_count is not None:
        print(f"Rows rejected by the parser: {reject_count:,}\n")
    else:
        print()


def main():
    if not RAW_CSV.exists():
        sys.exit(f"Cannot find {RAW_CSV}. Run this from the project root.")

    con = duckdb.connect()

    if not PARQUET.exists():
        convert(con)
    else:
        print("Parquet already exists, skipping conversion.")
        print("Delete data/raw/complaints.parquet if you want to rebuild it.\n")

    con.execute(f"CREATE VIEW c AS SELECT * FROM read_parquet('{PARQUET.as_posix()}')")

    emit("# CFPB Corpus Profile")
    emit()
    emit("Generated by `src/profile_corpus.py`. Source: CFPB Consumer Complaint Database.")
    emit()

    # ---- Data quality: parser rejects ------------------------------------
    if reject_count is not None:
        emit("## Data quality: parser rejects")
        emit()
        emit(f"Rows rejected during CSV parsing: **{reject_count:,}**")
        emit()
        emit("These are malformed rows, typically consumer narratives containing "
             "unbalanced quote characters that break field alignment. They are "
             "excluded from the Parquet file. This is a real defect in the source "
             "data, not a processing choice, and the count belongs in the data "
             "quality section of the BRD.")
        emit()

    # ---- Columns ---------------------------------------------------------
    cols = con.execute("DESCRIBE c").fetchall()
    emit("## Columns")
    emit()
    for i, col in enumerate(cols, 1):
        emit(f"{i}. `{col[0]}`")
    emit()

    # ---- Headline counts -------------------------------------------------
    total, with_narr = con.execute(f"""
        SELECT
            COUNT(*),
            COUNT(*) FILTER (WHERE {NARR} IS NOT NULL AND TRIM({NARR}) <> '')
        FROM c
    """).fetchone()

    pct = 100.0 * with_narr / total if total else 0

    emit("## Headline")
    emit()
    table(
        [
            ("Total complaints parsed", f"{total:,}"),
            ("With a consumer narrative", f"{with_narr:,}"),
            ("Share carrying a narrative", f"{pct:.1f}%"),
        ],
        ["Measure", "Value"],
    )

    # ---- Date range ------------------------------------------------------
    dmin, dmax = con.execute("""
        SELECT MIN(TRY_CAST("Date received" AS DATE)),
               MAX(TRY_CAST("Date received" AS DATE))
        FROM c
    """).fetchone()
    emit(f"Date range: **{dmin}** to **{dmax}**")
    emit()

    # ---- Narrative volume by year ---------------------------------------
    rows = con.execute(f"""
        SELECT EXTRACT(YEAR FROM TRY_CAST("Date received" AS DATE)) AS yr,
               COUNT(*) AS n
        FROM c
        WHERE {NARR} IS NOT NULL AND TRIM({NARR}) <> ''
        GROUP BY yr ORDER BY yr
    """).fetchall()
    emit("## Narratives by year")
    emit()
    table([(int(y), f"{n:,}") for y, n in rows if y is not None], ["Year", "Narratives"])

    # ---- Product distribution -------------------------------------------
    prod_rows = con.execute(f"""
        SELECT "Product", COUNT(*) AS n,
               ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER (), 2) AS pct
        FROM c
        WHERE {NARR} IS NOT NULL AND TRIM({NARR}) <> ''
        GROUP BY "Product" ORDER BY n DESC
    """).fetchall()
    emit("## Product distribution (narratives only)")
    emit()
    emit(f"Distinct products: **{len(prod_rows)}**")
    emit()
    table([(p, f"{n:,}", f"{q}%") for p, n, q in prod_rows], ["Product", "Count", "Share"])

    # ---- Taxonomy cardinality -------------------------------------------
    n_issue, n_subissue, n_subproduct = con.execute(f"""
        SELECT COUNT(DISTINCT "Issue"),
               COUNT(DISTINCT "Sub-issue"),
               COUNT(DISTINCT "Sub-product")
        FROM c
        WHERE {NARR} IS NOT NULL AND TRIM({NARR}) <> ''
    """).fetchone()

    emit("## Taxonomy cardinality (narratives only)")
    emit()
    table(
        [
            ("Distinct Product values", len(prod_rows)),
            ("Distinct Sub-product values", n_subproduct),
            ("Distinct Issue values", n_issue),
            ("Distinct Sub-issue values", n_subissue),
        ],
        ["Level", "Distinct values"],
    )

    # ---- Rare class check ------------------------------------------------
    rare = con.execute(f"""
        WITH t AS (
            SELECT "Issue" AS iss, COUNT(*) AS n
            FROM c
            WHERE {NARR} IS NOT NULL AND TRIM({NARR}) <> ''
            GROUP BY "Issue"
        )
        SELECT
            COUNT(*) FILTER (WHERE n < 50),
            COUNT(*) FILTER (WHERE n < 200),
            COUNT(*)
        FROM t
    """).fetchone()
    emit("## Rare Issue classes")
    emit()
    table(
        [
            ("Issue values with fewer than 50 narratives", rare[0]),
            ("Issue values with fewer than 200 narratives", rare[1]),
            ("Total distinct Issue values", rare[2]),
        ],
        ["Measure", "Count"],
    )
    emit("Classes below roughly 50 examples are candidates to exclude from "
         "automation entirely.")
    emit()

    # ---- Top issues ------------------------------------------------------
    rows = con.execute(f"""
        SELECT "Issue", COUNT(*) AS n
        FROM c
        WHERE {NARR} IS NOT NULL AND TRIM({NARR}) <> ''
        GROUP BY "Issue" ORDER BY n DESC LIMIT 15
    """).fetchall()
    emit("## Top 15 Issue values")
    emit()
    table([(i, f"{n:,}") for i, n in rows], ["Issue", "Count"])

    # ---- Narrative length ------------------------------------------------
    stats = con.execute(f"""
        SELECT
            ROUND(AVG(LENGTH({NARR}))),
            QUANTILE_CONT(LENGTH({NARR}), 0.10),
            QUANTILE_CONT(LENGTH({NARR}), 0.50),
            QUANTILE_CONT(LENGTH({NARR}), 0.90),
            QUANTILE_CONT(LENGTH({NARR}), 0.99),
            MAX(LENGTH({NARR}))
        FROM c
        WHERE {NARR} IS NOT NULL AND TRIM({NARR}) <> ''
    """).fetchone()
    emit("## Narrative length (characters)")
    emit()
    table(
        [
            ("Mean", f"{stats[0]:,.0f}"),
            ("10th percentile", f"{stats[1]:,.0f}"),
            ("Median", f"{stats[2]:,.0f}"),
            ("90th percentile", f"{stats[3]:,.0f}"),
            ("99th percentile", f"{stats[4]:,.0f}"),
            ("Longest", f"{stats[5]:,.0f}"),
        ],
        ["Measure", "Characters"],
    )

    # ---- Redaction density -----------------------------------------------
    red = con.execute(f"""
        SELECT
            ROUND(100.0 * COUNT(*) FILTER (WHERE {NARR} LIKE '%XXXX%') / COUNT(*), 2),
            ROUND(AVG((LENGTH({NARR}) - LENGTH(REPLACE({NARR}, 'XXXX', ''))) / 4.0), 2),
            ROUND(100.0 * AVG(
                (LENGTH({NARR}) - LENGTH(REPLACE({NARR}, 'XXXX', ''))) * 1.0
                / NULLIF(LENGTH({NARR}), 0)
            ), 2)
        FROM c
        WHERE {NARR} IS NOT NULL AND TRIM({NARR}) <> ''
    """).fetchone()
    emit("## Redaction density")
    emit()
    table(
        [
            ("Narratives containing at least one XXXX", f"{red[0]}%"),
            ("Mean XXXX tokens per narrative", red[1]),
            ("Mean share of characters redacted", f"{red[2]}%"),
        ],
        ["Measure", "Value"],
    )
    emit("High redaction is a known failure mode: if XXXX removed the "
         "disambiguating entity, the correct behaviour is to abstain rather "
         "than guess.")
    emit()

    # ---- Sample narratives -----------------------------------------------
    samples = con.execute(f"""
        SELECT "Product", "Issue", SUBSTR({NARR}, 1, 400)
        FROM c
        WHERE {NARR} IS NOT NULL
          AND LENGTH({NARR}) BETWEEN 400 AND 900
        USING SAMPLE 3 ROWS
    """).fetchall()
    emit("## Three sample narratives")
    emit()
    for p, i, t in samples:
        emit(f"**{p} / {i}**")
        emit()
        emit("> " + t.replace("\n", " ").strip() + " ...")
        emit()

    OUT_MD.parent.mkdir(parents=True, exist_ok=True)
    OUT_MD.write_text("\n".join(report), encoding="utf-8")
    print(f"\nWritten to {OUT_MD}")


if __name__ == "__main__":
    main()
