"""
Step 5 - Taxonomy drift analysis.

Run from the project root:
    python src/taxonomy_drift.py

Why this exists:
    The profile reported 21 distinct Product values, but several are the same
    category renamed as CFPB revised its taxonomy over 15 years. A classifier
    cannot be built on a label set that shifted underneath the data, so before
    any modelling we establish which labels were retired, which are renames,
    and which time window has a stable taxonomy.

Output:
    docs/02_taxonomy_drift.md
"""

from pathlib import Path
import sys
import duckdb

ROOT = Path(__file__).resolve().parent.parent
PARQUET = ROOT / "data" / "raw" / "complaints.parquet"
OUT_MD = ROOT / "docs" / "02_taxonomy_drift.md"

NARR = '"Consumer complaint narrative"'
HAS_NARR = f"{NARR} IS NOT NULL AND TRIM({NARR}) <> ''"

report = []


def emit(text=""):
    print(text)
    report.append(text)


def table(rows, headers):
    emit("| " + " | ".join(headers) + " |")
    emit("|" + "|".join(["---"] * len(headers)) + "|")
    for r in rows:
        emit("| " + " | ".join("" if v is None else str(v) for v in r) + " |")
    emit()


def main():
    if not PARQUET.exists():
        sys.exit(f"Cannot find {PARQUET}. Run profile_corpus.py first.")

    con = duckdb.connect()
    con.execute(f"""
        CREATE VIEW c AS
        SELECT *,
               TRY_CAST("Date received" AS DATE) AS dt,
               EXTRACT(YEAR FROM TRY_CAST("Date received" AS DATE)) AS yr
        FROM read_parquet('{PARQUET.as_posix()}')
    """)

    emit("# Taxonomy Drift Analysis")
    emit()
    emit("Generated by `src/taxonomy_drift.py`. Narratives only.")
    emit()
    emit("The corpus spans 15 years. CFPB revised its Product and Issue taxonomy "
         "several times in that period. This document establishes which labels "
         "were retired, which are renames of one another, and which time window "
         "carries a stable taxonomy suitable for modelling.")
    emit()

    # ---- 1. Product lifespans -------------------------------------------
    rows = con.execute(f"""
        SELECT "Product",
               MIN(dt) AS first_seen,
               MAX(dt) AS last_seen,
               COUNT(*) AS n,
               COUNT(*) FILTER (WHERE yr >= 2024) AS n_recent
        FROM c
        WHERE {HAS_NARR}
        GROUP BY "Product"
        ORDER BY n DESC
    """).fetchall()

    emit("## Product lifespans")
    emit()
    emit("A product whose `last_seen` is well before today has been retired. "
         "A product with zero recent narratives is dead label space.")
    emit()
    table(
        [(p, str(a), str(b), f"{n:,}", f"{r:,}") for p, a, b, n, r in rows],
        ["Product", "First seen", "Last seen", "Total", "Since 2024"],
    )

    retired = [p for p, a, b, n, r in rows if r == 0]
    emit(f"**Products with no narratives since 2024: {len(retired)}**")
    emit()
    for p in retired:
        emit(f"- {p}")
    emit()

    # ---- 2. Suspected renames -------------------------------------------
    emit("## Suspected renames")
    emit()
    emit("Where one label stops within roughly a quarter of another starting, "
         "and both describe the same domain, the second is almost certainly a "
         "rename of the first rather than a new category.")
    emit()

    groups = {
        "Credit reporting": [
            "Credit reporting",
            "Credit reporting, credit repair services, or other personal consumer reports",
            "Credit reporting or other personal consumer reports",
        ],
        "Credit card": [
            "Credit card",
            "Credit card or prepaid card",
            "Prepaid card",
        ],
        "Payday / installment lending": [
            "Payday loan",
            "Payday loan, title loan, or personal loan",
            "Payday loan, title loan, personal loan, or advance loan",
            "Consumer Loan",
        ],
        "Bank account": [
            "Bank account or service",
            "Checking or savings account",
        ],
        "Money transfer": [
            "Money transfers",
            "Money transfer, virtual currency, or money service",
            "Virtual currency",
        ],
        "Student loan": ["Student loan"],
        "Mortgage": ["Mortgage"],
        "Debt collection": ["Debt collection", "Debt or credit management"],
        "Vehicle loan": ["Vehicle loan or lease"],
    }

    for family, members in groups.items():
        quoted = ", ".join("'" + m.replace("'", "''") + "'" for m in members)
        found = con.execute(f"""
            SELECT "Product", MIN(dt), MAX(dt), COUNT(*)
            FROM c
            WHERE {HAS_NARR} AND "Product" IN ({quoted})
            GROUP BY "Product" ORDER BY MIN(dt)
        """).fetchall()
        if not found:
            continue
        emit(f"### {family}")
        emit()
        table(
            [(p, str(a), str(b), f"{n:,}") for p, a, b, n in found],
            ["Label", "First seen", "Last seen", "Narratives"],
        )

    # ---- 3. Distinct labels per year ------------------------------------
    rows = con.execute(f"""
        SELECT yr,
               COUNT(DISTINCT "Product") AS n_prod,
               COUNT(DISTINCT "Issue") AS n_issue,
               COUNT(DISTINCT "Sub-issue") AS n_subissue,
               COUNT(*) AS n
        FROM c
        WHERE {HAS_NARR} AND yr IS NOT NULL
        GROUP BY yr ORDER BY yr
    """).fetchall()

    emit("## Label cardinality by year")
    emit()
    emit("A stable window is one where the distinct label count stops moving.")
    emit()
    table(
        [(int(y), p, i, s, f"{n:,}") for y, p, i, s, n in rows],
        ["Year", "Products", "Issues", "Sub-issues", "Narratives"],
    )

    # ---- 4. Issue churn between adjacent years --------------------------
    emit("## Issue churn between adjacent years")
    emit()
    emit("`Introduced` counts Issue values present this year but absent last year. "
         "`Retired` counts the reverse. A stable taxonomy shows near-zero churn.")
    emit()

    churn = con.execute(f"""
        WITH iy AS (
            SELECT DISTINCT yr, "Issue" AS iss
            FROM c WHERE {HAS_NARR} AND yr IS NOT NULL
        )
        SELECT a.yr,
               COUNT(*) FILTER (WHERE b.iss IS NULL) AS introduced
        FROM iy a
        LEFT JOIN iy b ON b.iss = a.iss AND b.yr = a.yr - 1
        GROUP BY a.yr ORDER BY a.yr
    """).fetchall()

    retired_rows = con.execute(f"""
        WITH iy AS (
            SELECT DISTINCT yr, "Issue" AS iss
            FROM c WHERE {HAS_NARR} AND yr IS NOT NULL
        )
        SELECT a.yr + 1 AS yr,
               COUNT(*) FILTER (WHERE b.iss IS NULL) AS retired
        FROM iy a
        LEFT JOIN iy b ON b.iss = a.iss AND b.yr = a.yr + 1
        GROUP BY a.yr ORDER BY a.yr
    """).fetchall()

    ret_map = {int(y): r for y, r in retired_rows}
    table(
        [(int(y), n, ret_map.get(int(y), 0)) for y, n in churn],
        ["Year", "Introduced", "Retired"],
    )

    # ---- 5. Candidate windows -------------------------------------------
    emit("## Candidate modelling windows")
    emit()

    windows = []
    for start in (2020, 2022, 2023, 2024, 2025):
        r = con.execute(f"""
            SELECT COUNT(*),
                   COUNT(DISTINCT "Product"),
                   COUNT(DISTINCT "Issue"),
                   COUNT(DISTINCT "Sub-issue")
            FROM c
            WHERE {HAS_NARR} AND yr >= {start}
        """).fetchone()
        windows.append((f"{start} onwards", f"{r[0]:,}", r[1], r[2], r[3]))

    table(windows, ["Window", "Narratives", "Products", "Issues", "Sub-issues"])
    emit("The window to choose is the earliest one where label counts have "
         "settled and volume is still ample. That decision, and its rationale, "
         "belongs in the BRD as a documented scoping constraint.")
    emit()

    # ---- 6. Rare issues within the likely window ------------------------
    for start in (2023, 2024):
        r = con.execute(f"""
            WITH t AS (
                SELECT "Issue" AS iss, COUNT(*) AS n
                FROM c WHERE {HAS_NARR} AND yr >= {start}
                GROUP BY "Issue"
            )
            SELECT COUNT(*) FILTER (WHERE n < 50),
                   COUNT(*) FILTER (WHERE n < 200),
                   COUNT(*)
            FROM t
        """).fetchone()
        emit(f"**{start} onwards:** {r[2]} distinct Issue values, "
             f"{r[1]} with fewer than 200 narratives, {r[0]} with fewer than 50.")
        emit()

    OUT_MD.parent.mkdir(parents=True, exist_ok=True)
    OUT_MD.write_text("\n".join(report), encoding="utf-8")
    print(f"\nWritten to {OUT_MD}")


if __name__ == "__main__":
    main()
